# Generated by Django 6.1.1 on 2026-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentlink",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
