# Generated by Django 6.1.1 on 2026-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0002_studentlink_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='student_name',
        ),
        migrations.AddField(
            model_name='studentlink',
            name='student_name',
            field=models.CharField(default='', help_text="Student's name set by the teacher", max_length=255),
            preserve_default=False,
        ),
    ]
