# Generated by Django 6.1.1 on 2026-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broadcast", "0003_remove_channel_student_name_studentlink_student_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentlink",
            name="label",
        ),
        migrations.AlterField(
            model_name="studentlink",
            name="student_name",
            field=models.CharField(max_length=255),
        ),
    ]
