# Generated by Django 6.1.1 on 2026-10-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0006_sentmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintoken',
            name='teacher',
        ),
        migrations.AddField(
            model_name='logintoken',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
    ]
