# Generated by Django 6.1.1 on 2026-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0008_alter_logintoken_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sentmessage',
            index=models.Index(fields=['channel', '-sent_at'], name='broadcast_s_channel_43bd03_idx'),
        ),
    ]
