# Generated by Django 6.1.1 on 2026-10-08 04:54

import broadcast.fields
from django.db import migrations, models


def encrypt_existing_webhooks(apps, schema_editor):
    """Encrypt plaintext webhook URLs and populate hashes for existing rows.

    The fake model returned by ``apps.get_model`` does *not* invoke
    custom field methods (from_db_value / get_prep_value), so we
    read and write raw values directly.
    """
    from broadcast.crypto import encrypt_value, hash_value

    Channel = apps.get_model('broadcast', 'Channel')
    for channel in Channel.objects.all().iterator():
        raw_url = channel.webhook_url
        if not raw_url:
            continue
        channel.webhook_url = encrypt_value(raw_url)
        channel.webhook_url_hash = hash_value(raw_url)
        channel.save(update_fields=['webhook_url', 'webhook_url_hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0010_ratelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='webhook_url_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash for indexed duplicate lookups.', max_length=64),
        ),
        migrations.AlterField(
            model_name='channel',
            name='webhook_url',
            field=broadcast.fields.EncryptedTextField(),
        ),
        migrations.RunPython(
            encrypt_existing_webhooks,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['email'], name='broadcast_l_email_b15c89_idx'),
        ),
        migrations.AddIndex(
            model_name='logintoken',
            index=models.Index(fields=['expires_at', 'used'], name='broadcast_l_expires_9c946a_idx'),
        ),
    ]
