# Generated by Django 6.1.1 on 2026-10-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast', '0011_logintoken_indexes_channel_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratelimit',
            name='reset_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
